### PR TITLE
Randomcad

### LINKED ISSUE #9: Write Code gnerator

### LINKED ISSUE #30: Implement the calcdef commands

### LINKED ISSUE #31: Implement the pathdef commands

### LINKED ISSUE #41: Color UnitTest is failing
With the changes I've made the Colore UnitTest doesn't work any more @CompScience55, could you maybe find out what the problem is?
Or should/must I do that?

_Originally posted by @RandomCad in https://github.com/RandomCad/Turtel/issues/28#issuecomment-2705888235_

### PR DESCRIPTION
**Pull request by RandomCad**

### CODE REVIEW

**Comment by RandomCad** [comment]
With the changes I've made the Colore UnitTest doesn't work any more @CompScience55, could you maybe find out what the problem is?
Or should/must I do that?

File: UnitTest/TopLevelVisitor.cpp [hunk 1]
```diff
@@ -20,6 +18,304 @@ std::regex matchClosingCrlBracket = std::regex("\\s*\\}\\s*");
...
+
+  test.llvm.llvmFile.seekg(0);
+  
+  ASSERT_EQ(ret, 1);
+
+  test.llvm.CallLLVM();
+  ASSERT_TRUE(std::filesystem::exists(testFile));
+}
+
+#if FALSE
```
Comment (RandomCad) [inline UnitTest/TopLevelVisitor.cpp]: reactivate the following UnitTests

Comment (RandomCad) [reply UnitTest/TopLevelVisitor.cpp]: mostly done
